apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: "agent"
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:latest
    resources:
      limits:
        memory: "512Mi"
        cpu: "512m"
  - name: docker
    image: docker:24.0.5-dind
    command: ["dockerd-entrypoint.sh"]
    args: ["--host=tcp://0.0.0.0:2375"]
    securityContext:
      privileged: true
    volumeMounts:
    - name: docker-sock
      mountPath: /var/run/docker.sock
  volumes:
  - name: docker-sock
    emptyDir: {}
